import { Moment } from 'moment';
export class Retour {
  idPriseEnCharge: number;
  noDemande: string;
  dateDemande : Date;
  dateDemandeVisu : string;
  noFacture: string;
  idPrescripteur: number;
  idVictime: number;
  idDemande: number;
  idCourse: number;
  idChauffeur: number;
  nomPrescripteur : string;
  depDemande : String;
  nomChauffeur : string;
  nomVictime : string;
  nomUsage : string;
  prenom : string;
  adresse : string;
  telephone : string;
  mail : string;
  age : number;
  enfantCharge : number;
  infoComplementaire : string;
  motif: string;
  enfantPresent: boolean;
  nbEnfant: number;
  particularite: string;
  adresseDepart: string;
  adresseArrivee: string;
  allerRetour: boolean;
  dateCourse: Date;
  heureCourseDebut: Date;
  heureCourseFin: Date;
  dateCourseVisu: string;
  heureCourseDebutVisu: string;
  heureCourseFinVisu: string;
  montant: number;
  peage: number;
}
